### ISSUE TITLE
full data reshaping, predicting, and saving output for SVM i fu=inf the following issues

### ISSUE THREAD

**Issue by zafor44** [waleedgeo/lulc_py#1]
reshaped full data shape  for prediction:  (309778, 4)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

AttributeError: 'DatasetReader' object has no attribute 'met'

**Comment by waleedgeo** [comment]
Dear,

It was just a typo issue, just replace met with meta. I have updated the codes, please check.
